Magick++: Magick::DrawableDashArray Class Reference
Magick::DrawableDashArray Class Reference
#include <Drawable.h>
Public Member Functions
DrawableDashArray (const double *dasharray_)
DrawableDashArray (const size_t *dasharray_)
DrawableDashArray (const Magick::DrawableDashArray &original_)
~DrawableDashArray (void)
void operator() (MagickCore::DrawingWand *context_) const
DrawableBase * copy () const
void dasharray (const double *dasharray_)
void dasharray (const size_t *dasharray_)
const double * dasharray (void) const
DrawableDashArray & operator= (const Magick::DrawableDashArray &original_)
Public Member Functions inherited from Magick::DrawableBase
DrawableBase (void)
virtual ~DrawableBase (void)
Detailed Description
Definition at line 1662 of file Drawable.h.
Constructor & Destructor Documentation
DrawableDashArray() [1/3]
Magick::DrawableDashArray::DrawableDashArray (const double * dasharray_)
Definition at line 1042 of file Drawable.cpp.
References dasharray().
DrawableDashArray() [2/3]
Magick::DrawableDashArray::DrawableDashArray (const size_t * dasharray_)
Definition at line 1050 of file Drawable.cpp.
References dasharray().
DrawableDashArray() [3/3]
Magick::DrawableDashArray::DrawableDashArray (const Magick::DrawableDashArray & original_)
Definition at line 1057 of file Drawable.cpp.
~DrawableDashArray()
Magick::DrawableDashArray::~DrawableDashArray (void)
Definition at line 1069 of file Drawable.cpp.
Member Function Documentation
copy()
Magick::DrawableBase * Magick::DrawableDashArray::copy () const virtual
Implements Magick::DrawableBase.
Definition at line 1098 of file Drawable.cpp.
dasharray() [1/3]
void Magick::DrawableDashArray::dasharray (const double * dasharray_)
Definition at line 1102 of file Drawable.cpp.
dasharray() [2/3]
void Magick::DrawableDashArray::dasharray (const size_t * dasharray_)
Definition at line 1131 of file Drawable.cpp.
dasharray() [3/3]
const double* Magick::DrawableDashArray::dasharray (void) const inline
Definition at line 1680 of file Drawable.h.
Referenced by DrawableDashArray().
operator()()
void Magick::DrawableDashArray::operator() (MagickCore::DrawingWand * context_) const virtual
Implements Magick::DrawableBase.
Definition at line 1094 of file Drawable.cpp.
operator=()
Magick::DrawableDashArray & Magick::DrawableDashArray::operator= (const Magick::DrawableDashArray & original_)
Definition at line 1076 of file Drawable.cpp.
The documentation for this class was generated from the following files:
Drawable.h
Drawable.cpp