Magick++: piddle.cpp File Reference
piddle.cpp File Reference
#include <Magick++.h>
#include <string>
#include <iostream>
Functions
int main (int, char **argv)
Function Documentation
main()
int main (int , char ** argv)
Definition at line 17 of file piddle.cpp.
References Magick::Color, Magick::Image::columns(), Magick::Image::compressType(), Magick::Image::depth(), Magick::Image::draw(), Magick::InitializeMagick(), Magick::Image::rows(), and Magick::Image::write().