Magick++: zoom.cpp File Reference
zoom.cpp File Reference
#include <Magick++.h>
#include <iostream>
#include <string>
Functions
static void Usage (char **argv)
static void ParseError (int position, char **argv)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 34 of file zoom.cpp.
References Magick::Image::columns(), Magick::Image::density(), Magick::Image::filterType(), Magick::Geometry, Magick::Geometry::height(), Magick::InitializeMagick(), Magick::Geometry::isValid(), ParseError(), Magick::Image::rows(), Magick::Image::sample(), Magick::Image::scale(), Usage(), Magick::Geometry::width(), Magick::Image::write(), and Magick::Image::zoom().
ParseError()
static void ParseError (int position, char ** argv) static
Definition at line 27 of file zoom.cpp.
References Usage().
Referenced by main().
Usage()
static void Usage (char ** argv) static
Definition at line 17 of file zoom.cpp.
Referenced by main(), and ParseError().